Select * from customer limit 20

--Q1. What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount)as revenue
FROM customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as "Avergae Product rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount),2) as "Average Purchase amount"
FROM customer
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100 * SUM(
	CASE WHEN discount_applied = 'Yes' 
		THEN 1 
		ELSE 0 
		END)/COUNT(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
Limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and 
-- show the count of each segment. 
WITH customer_type AS (

SELECT customer_id,previous_purchases,
CASE 
	 WHEN previous_purchases = 1 THEN 'New customer'
	 WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning customer'
	 ElSE 'Loyal customer'
	 END AS customer_segment
FROM customer
)

SELECT customer_segment, COUNT(*) as "Number of customers"
FROM customer_type
GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category
WITH item_counts as (
SELECT category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
FROM customer
GROUP BY category, item_purchased)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases >5
GROUP BY subscription_status

--Q10. what is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER by total_revenue desc;